import Head from 'next/head'
import Image from 'next/image'
import { PageLayout } from '../components/layout/PageLayout'
import { Home } from '../components/organisms/Home'
import { drupal } from "../lib/drupal"
import styles from '../styles/Home.module.css'

export default function HomePage({ nodes }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <PageLayout>
      <div>
        <h1 className="mb-10 text-6xl font-black">Latest Articles.</h1>
        {nodes?.length ? (
          nodes.map((node) => (
            <div key={node.id}>
              <a className="no-underline hover:text-blue-600">
                <h2 className="mb-4 text-4xl font-bold">{node.title}</h2>
              </a>
              <div className="mb-4 text-gray-600">
                {node.uid?.display_name ? (
                  <span>
                    Posted by{" "}
                    <span className="font-semibold">{node.uid?.display_name}</span>
                  </span>
                ) : null}
              </div>
              <hr className="my-20" />
            </div>
          ))
        ) : (
          <p className="py-4">No nodes found</p>
        )}
      </div>
      </PageLayout>
    </>
  )
}

export async function getStaticProps(
  context
) {
  const nodes = await drupal.getResourceCollectionFromContext(
    "node--article",
    context,
    {
      params: {
        "filter[status]": 1,
        "fields[node--article]": "title,path,field_image,uid,created",
        include: "field_image,uid",
        sort: "-created",
      },
    }
  )

  return {
    props: {
      nodes,
    },
  }
}
